# Generated by Django 4.1.7 on 2024-02-28 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_skill_slug_alter_useremployerprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userFreelancer', to=settings.AUTH_USER_MODEL),
        ),
    ]
