# Generated by Django 4.1.7 on 2024-03-02 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_alter_userprofile_user'),
        ('content', '0001_initial'),
        ('options', '0003_requestfreelancer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestEmployer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_accept', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestEmployer', to=settings.AUTH_USER_MODEL)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancerRequest', to='accounts.userprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.project')),
            ],
        ),
    ]
